version: 1.2
workflows:
  - name: safeconstructor
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /dockstore.cwl.json
!!java.util.Date
date: 25
month: 12
year: 2016
